x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-restart-policy: &restart-policy
  restart: unless-stopped

x-cosmos-defaults: &cosmos-defaults
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  builder:
    restart: "no"
    build:
      context: ./builder
      dockerfile: Dockerfile
    image: builder:${DAEMON_NAME:-cosmos}
    pull_policy: never
    environment:
      - NODE_VERSION=${NODE_VERSION}
      - NODE_REPO=${NODE_REPO}
      - DAEMON_NAME=${DAEMON_NAME}
      - FORCE_REBUILD=${FORCE_REBUILD:-}
    volumes:
      - node-builds:/builds

  cosmos:
    build:
      context: ./cosmos
      dockerfile: Dockerfile.source
      args:
        - NODE_VERSION=${NODE_VERSION}
        - USER=${DAEMON_NAME:-cosmos}
        - UID=${HOST_UID:-1000}
        - GID=${HOST_GID:-1000}
    image: ${DAEMON_NAME:-cosmos}:local
    pull_policy: never
    user: ${DAEMON_NAME:-cosmos}
    container_name: ${NETWORK}
    <<: *cosmos-defaults
    stop_grace_period: 5m
    environment:
      - NODE_VERSION=${NODE_VERSION}
      - NODE_REPO=${NODE_REPO}
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
      - MIN_GAS_PRICE=${MIN_GAS_PRICE}
      - PRUNING_STRATEGY=${PRUNING_STRATEGY:-default}
      - PRUNING_KEEP_RECENT=${PRUNING_KEEP_RECENT}
      - PRUNING_INTERVAL=${PRUNING_INTERVAL}
      - NETWORK=${NETWORK}
      - MONIKER=${MONIKER}
      - RPC_PORT=${RPC_PORT:-26657}
      - P2P_PORT=${P2P_PORT:-26656}
      - GRPC_PORT=${GRPC_PORT:-9090}
      - GRPC_WEB_PORT=${GRPC_WEB_PORT:-9091}
      - REST_PORT=${REST_PORT:-1317}
      - SNAPSHOT=${SNAPSHOT}
      - SNAPSHOT_API_URL=${SNAPSHOT_API_URL:-}
      - SNAPSHOT_BASE_URL=${SNAPSHOT_BASE_URL:-}
      - SEEDS=${SEEDS}
      - PERSISTENT_PEERS=${PERSISTENT_PEERS}
      - MAX_INBOUND_PEERS=${MAX_INBOUND_PEERS:-400}
      - MAX_OUTBOUND_PEERS=${MAX_OUTBOUND_PEERS:-400}
      - P2P_PEX=${P2P_PEX:-true}
      - P2P_ADDR_BOOK_STRICT=${P2P_ADDR_BOOK_STRICT:-true}
      - P2P_FLUSH_THROTTLE_TIMEOUT=${P2P_FLUSH_THROTTLE_TIMEOUT:-30s}
      - P2P_DIAL_TIMEOUT=${P2P_DIAL_TIMEOUT:-10s}
      - P2P_HANDSHAKE_TIMEOUT=${P2P_HANDSHAKE_TIMEOUT:-3s}
      - P2P_ALLOW_DUPLICATE_IP=${P2P_ALLOW_DUPLICATE_IP:-false}
      - PRIVATE_PEER_IDS=${PRIVATE_PEER_IDS}
      - EXTERNAL_ADDRESS=${EXTERNAL_ADDRESS}
      - GENESIS_URL=${GENESIS_URL}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_LOG_FORMAT=${NODE_LOG_FORMAT:-plain}
      - FAST_SYNC=${FAST_SYNC:-true}
      - PROXY_APP=${PROXY_APP:-tcp://127.0.0.1:26658}
      - P2P_SEND_RATE=${P2P_SEND_RATE:-5120000}
      - P2P_RECV_RATE=${P2P_RECV_RATE:-5120000}
      - P2P_MAX_PACKET_MSG_PAYLOAD_SIZE=${P2P_MAX_PACKET_MSG_PAYLOAD_SIZE:-1024}
      - P2P_SEED_MODE=${P2P_SEED_MODE:-false}
      - P2P_UNCONDITIONAL_PEER_IDS=${P2P_UNCONDITIONAL_PEER_IDS:-}
      - P2P_PERSISTENT_PEERS_MAX_DIAL_PERIOD=${P2P_PERSISTENT_PEERS_MAX_DIAL_PERIOD:-0s}
      - RPC_CORS_ALLOWED_ORIGINS=${RPC_CORS_ALLOWED_ORIGINS:-["*"]}
      - RPC_MAX_OPEN_CONNECTIONS=${RPC_MAX_OPEN_CONNECTIONS:-900}
      - RPC_GRPC_MAX_OPEN_CONNECTIONS=${RPC_GRPC_MAX_OPEN_CONNECTIONS:-900}
      - STATESYNC_ENABLE=${STATESYNC_ENABLE:-false}
      - STATESYNC_RPC_SERVERS=${STATESYNC_RPC_SERVERS}
      - STATESYNC_TRUST_PERIOD=${STATESYNC_TRUST_PERIOD:-360h0m0s}
      - CONSENSUS_TIMEOUT_COMMIT=${CONSENSUS_TIMEOUT_COMMIT:-5s}
      - CONSENSUS_CREATE_EMPTY_BLOCKS=${CONSENSUS_CREATE_EMPTY_BLOCKS:-true}
      - CONSENSUS_TIMEOUT_PROPOSE=${CONSENSUS_TIMEOUT_PROPOSE:-3s}
      - CONSENSUS_TIMEOUT_PROPOSE_DELTA=${CONSENSUS_TIMEOUT_PROPOSE_DELTA:-500ms}
      - CONSENSUS_TIMEOUT_PREVOTE=${CONSENSUS_TIMEOUT_PREVOTE:-1s}
      - CONSENSUS_TIMEOUT_PREVOTE_DELTA=${CONSENSUS_TIMEOUT_PREVOTE_DELTA:-500ms}
      - CONSENSUS_TIMEOUT_PRECOMMIT=${CONSENSUS_TIMEOUT_PRECOMMIT:-1s}
      - CONSENSUS_TIMEOUT_PRECOMMIT_DELTA=${CONSENSUS_TIMEOUT_PRECOMMIT_DELTA:-500ms}
      - CONSENSUS_SKIP_TIMEOUT_COMMIT=${CONSENSUS_SKIP_TIMEOUT_COMMIT:-false}
      - CONSENSUS_CREATE_EMPTY_BLOCKS_INTERVAL=${CONSENSUS_CREATE_EMPTY_BLOCKS_INTERVAL:-0s}
      - CONSENSUS_PEER_GOSSIP_SLEEP_DURATION=${CONSENSUS_PEER_GOSSIP_SLEEP_DURATION:-100ms}
      - CONSENSUS_PEER_QUERY_MAJ23_SLEEP_DURATION=${CONSENSUS_PEER_QUERY_MAJ23_SLEEP_DURATION:-2s}
      - CONSENSUS_DOUBLE_SIGN_CHECK_HEIGHT=${CONSENSUS_DOUBLE_SIGN_CHECK_HEIGHT:-0}
      - MEMPOOL_SIZE=${MEMPOOL_SIZE:-5000}
      - MEMPOOL_CACHE_SIZE=${MEMPOOL_CACHE_SIZE:-10000}
      - MEMPOOL_RECHECK=${MEMPOOL_RECHECK:-true}
      - MEMPOOL_BROADCAST=${MEMPOOL_BROADCAST:-true}
      - MEMPOOL_MAX_TXS_BYTES=${MEMPOOL_MAX_TXS_BYTES:-1073741824}
      - MEMPOOL_MAX_TX_BYTES=${MEMPOOL_MAX_TX_BYTES:-1048576}
      - MEMPOOL_MAX_BATCH_BYTES=${MEMPOOL_MAX_BATCH_BYTES:-0}
      - MEMPOOL_KEEP_INVALID_TXS=${MEMPOOL_KEEP_INVALID_TXS:-false}
      - RPC_CORS_ALLOWED_METHODS=${RPC_CORS_ALLOWED_METHODS:-["HEAD", "GET", "POST"]}
      - RPC_CORS_ALLOWED_HEADERS=${RPC_CORS_ALLOWED_HEADERS:-["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]}
      - RPC_UNSAFE=${RPC_UNSAFE:-false}
      - RPC_MAX_SUBSCRIPTION_CLIENTS=${RPC_MAX_SUBSCRIPTION_CLIENTS:-100}
      - RPC_MAX_SUBSCRIPTIONS_PER_CLIENT=${RPC_MAX_SUBSCRIPTIONS_PER_CLIENT:-5}
      - RPC_EXPERIMENTAL_SUBSCRIPTION_BUFFER_SIZE=${RPC_EXPERIMENTAL_SUBSCRIPTION_BUFFER_SIZE:-200}
      - RPC_EXPERIMENTAL_WEBSOCKET_WRITE_BUFFER_SIZE=${RPC_EXPERIMENTAL_WEBSOCKET_WRITE_BUFFER_SIZE:-200}
      - RPC_EXPERIMENTAL_CLOSE_ON_SLOW_CLIENT=${RPC_EXPERIMENTAL_CLOSE_ON_SLOW_CLIENT:-false}
      - RPC_TIMEOUT_BROADCAST_TX_COMMIT=${RPC_TIMEOUT_BROADCAST_TX_COMMIT:-10s}
      - RPC_MAX_BODY_BYTES=${RPC_MAX_BODY_BYTES:-1000000}
      - RPC_MAX_HEADER_BYTES=${RPC_MAX_HEADER_BYTES:-1048576}
      - STATESYNC_TRUST_HEIGHT=${STATESYNC_TRUST_HEIGHT:-0}
      - STATESYNC_TRUST_HASH=${STATESYNC_TRUST_HASH}
      - STATESYNC_DISCOVERY_TIME=${STATESYNC_DISCOVERY_TIME:-15s}
      - STATESYNC_CHUNK_REQUEST_TIMEOUT=${STATESYNC_CHUNK_REQUEST_TIMEOUT:-10s}
      - STATESYNC_CHUNK_FETCHERS=${STATESYNC_CHUNK_FETCHERS:-4}
      - PROMETHEUS_ENABLED=${PROMETHEUS_ENABLED:-true}
      - PROMETHEUS_NAMESPACE=${PROMETHEUS_NAMESPACE:-tendermint}
      - PROMETHEUS_LISTEN_ADDR=${PROMETHEUS_LISTEN_ADDR:-:26660}
      - PROMETHEUS_MAX_OPEN_CONNECTIONS=${PROMETHEUS_MAX_OPEN_CONNECTIONS:-10}
      - FASTSYNC_VERSION=${FASTSYNC_VERSION:-v0}
      - TX_INDEX_INDEXER=${TX_INDEX_INDEXER:-kv}
      - DB_BACKEND=${DB_BACKEND:-goleveldb}
      - DB_DIR=${DB_DIR:-data}
      - ABCI=${ABCI:-socket}
      - FILTER_PEERS=${FILTER_PEERS:-false}
      - GOMAXPROCS=${GOMAXPROCS:-}
      - GOMEMLIMIT=${GOMEMLIMIT:-}
      - DAEMON_HOME=${DAEMON_HOME:-/cosmos}
      - DAEMON_NAME=${DAEMON_NAME:-cosmos}
      - DATA_DIR=${DATA_DIR:-/mnt/data/blockchain/${NETWORK}}
    ports:
      - ${P2P_PORT:-26656}:${P2P_PORT:-26656}/tcp
      - ${RPC_PORT:-26657}:${RPC_PORT:-26657}/tcp
      - ${GRPC_PORT:-9090}:${GRPC_PORT:-9090}/tcp
      - ${GRPC_WEB_PORT:-9091}:${GRPC_WEB_PORT:-9091}/tcp
      - ${REST_PORT:-1317}:${REST_PORT:-1317}/tcp
      - ${PROMETHEUS_PORT:-26660}:${PROMETHEUS_PORT:-26660}/tcp  # Prometheus metrics port
    depends_on:
      builder:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${RPC_PORT:-26657}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ${DATA_DIR:-/mnt/data/blockchain/${NETWORK}}:${DATA_DIR:-/mnt/data/blockchain/${NETWORK}}
      - node-builds:/builds
    entrypoint:
      - docker-entrypoint.sh

volumes:
  node-data:
  node-builds:
