x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  builder:
    restart: "no"
    build:
      context: ./builder
      dockerfile: Dockerfile
    image: builder:thornode
    pull_policy: never
    environment:
      - THORNODE_VERSION=${THORNODE_VERSION}
      - FORCE_REBUILD=${FORCE_REBUILD}
    volumes:
      - thornode-builds:/builds

  thorchain:
    build:
      context: ./thorchain
      dockerfile: Dockerfile.source
      args:
        - THORNODE_VERSION=${THORNODE_VERSION}
        - USER=thornode
    image: thorchain:local
    pull_policy: never
    user: thornode
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      - THORNODE_VERSION=${THORNODE_VERSION}
      - THORNODE_REPO=${THORNODE_REPO:-https://gitlab.com/thorchain/thornode}
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
      - NETWORK=${NETWORK}
      - MONIKER=${MONIKER}
      - RPC_PORT=${RPC_PORT:-27147}
      - P2P_PORT=${P2P_PORT:-27146}
      - GRPC_PORT=${GRPC_PORT:-9090}
      - GRPC_WEB_PORT=${GRPC_WEB_PORT:-9091}
      - REST_PORT=${REST_PORT:-1317}
      - SNAPSHOT=${SNAPSHOT}
      - SNAPSHOT_API_URL=${SNAPSHOT_API_URL:-https://snapshots.ninerealms.com/snapshots?prefix=thornode}
      - SNAPSHOT_BASE_URL=${SNAPSHOT_BASE_URL:-https://snapshots.ninerealms.com/snapshots/thornode/}
      - SEEDS=${SEEDS}
      - PERSISTENT_PEERS=${PERSISTENT_PEERS}
      - MAX_INBOUND_PEERS=${MAX_INBOUND_PEERS:-400}
      - MAX_OUTBOUND_PEERS=${MAX_OUTBOUND_PEERS:-400}
      - P2P_PEX=${P2P_PEX:-true}
      - P2P_ADDR_BOOK_STRICT=${P2P_ADDR_BOOK_STRICT:-true}
      - P2P_FLUSH_THROTTLE_TIMEOUT=${P2P_FLUSH_THROTTLE_TIMEOUT:-30s}
      - P2P_DIAL_TIMEOUT=${P2P_DIAL_TIMEOUT:-10s}
      - P2P_HANDSHAKE_TIMEOUT=${P2P_HANDSHAKE_TIMEOUT:-3s}
      - P2P_ALLOW_DUPLICATE_IP=${P2P_ALLOW_DUPLICATE_IP:-false}
      - PRIVATE_PEER_IDS=${PRIVATE_PEER_IDS}
      - EXTERNAL_ADDRESS=${EXTERNAL_ADDRESS}
      - GENESIS_URL=${GENESIS_URL:-https://storage.googleapis.com/public-snapshots-ninerealms/genesis/17562000.json}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-plain}
      - FAST_SYNC=${FAST_SYNC:-true}
      - PROXY_APP=${PROXY_APP:-tcp://127.0.0.1:26658}
      - P2P_SEND_RATE=${P2P_SEND_RATE:-5120000}
      - P2P_RECV_RATE=${P2P_RECV_RATE:-5120000}
      - P2P_MAX_PACKET_MSG_PAYLOAD_SIZE=${P2P_MAX_PACKET_MSG_PAYLOAD_SIZE:-1024}
      - P2P_SEED_MODE=${P2P_SEED_MODE:-false}
      - P2P_UNCONDITIONAL_PEER_IDS=${P2P_UNCONDITIONAL_PEER_IDS}
      - P2P_PERSISTENT_PEERS_MAX_DIAL_PERIOD=${P2P_PERSISTENT_PEERS_MAX_DIAL_PERIOD:-0s}
      - RPC_CORS_ALLOWED_ORIGINS=${RPC_CORS_ALLOWED_ORIGINS:-["*"]}
      - RPC_MAX_OPEN_CONNECTIONS=${RPC_MAX_OPEN_CONNECTIONS:-900}
      - RPC_GRPC_MAX_OPEN_CONNECTIONS=${RPC_GRPC_MAX_OPEN_CONNECTIONS:-900}
      - STATESYNC_ENABLE=${STATESYNC_ENABLE:-false}
      - STATESYNC_RPC_SERVERS=${STATESYNC_RPC_SERVERS}
      - STATESYNC_TRUST_PERIOD=${STATESYNC_TRUST_PERIOD:-360h0m0s}
      - CONSENSUS_TIMEOUT_COMMIT=${CONSENSUS_TIMEOUT_COMMIT:-5s}
      - CONSENSUS_CREATE_EMPTY_BLOCKS=${CONSENSUS_CREATE_EMPTY_BLOCKS:-true}
      - MEMPOOL_SIZE=${MEMPOOL_SIZE:-5000}
      - MEMPOOL_CACHE_SIZE=${MEMPOOL_CACHE_SIZE:-10000}
      - PROMETHEUS_ENABLED=${PROMETHEUS_ENABLED:-true}
      - PROMETHEUS_NAMESPACE=${PROMETHEUS_NAMESPACE:-tendermint}
      - FASTSYNC_VERSION=${FASTSYNC_VERSION:-v0}
      - GOMAXPROCS=${GOMAXPROCS}
      - GOMEMLIMIT=${GOMEMLIMIT}
      - DAEMON_HOME=/thornode
      - DAEMON_NAME=thornode
    ports:
      - ${P2P_PORT:-27146}:${P2P_PORT:-27146}/tcp
      - ${RPC_PORT:-27147}:${RPC_PORT:-27147}/tcp
      - ${GRPC_PORT:-9090}:${GRPC_PORT:-9090}/tcp
      - ${GRPC_WEB_PORT:-9091}:${GRPC_WEB_PORT:-9091}/tcp
      - ${REST_PORT:-1317}:${REST_PORT:-1317}/tcp
    depends_on:
      builder:
        condition: service_completed_successfully
    <<: *logging
    volumes:
      - /mnt/data/blockchain/:/thornode
      - thornode-builds:/builds
    entrypoint:
      - docker-entrypoint.sh
      - start
      - --home
      - /thornode

volumes:
  thornode-data:
  thornode-builds: