name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I considered...

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - label: New configuration option
        - label: New Docker service
        - label: Makefile improvement
        - label: Documentation enhancement
        - label: Script improvement
        - label: CI/CD enhancement
        - label: Security improvement
        - label: Performance optimization
        - label: Developer experience improvement

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Needed for production use
        - Critical - Blocking current use
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share them.
      placeholder: |
        This could be implemented by:
        1. Adding a new environment variable...
        2. Modifying the docker-compose.yml to...
        3. Creating a new script that...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature.
      placeholder: I need this feature because...
    validations:
      required: true

  - type: checkboxes
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing the implementation
        - label: I can help with documentation
        - label: I can provide feedback during development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
