name: Docker Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Verify Docker Compose files syntax
      run: |
        # Test main docker-compose file
        docker-compose -f cosmos.yml config --quiet
        echo "✅ cosmos.yml syntax is valid"
        
        # Test development override file if it exists
        if [ -f docker-compose.dev.yml ]; then
          docker-compose -f cosmos.yml -f docker-compose.dev.yml config --quiet
          echo "✅ docker-compose.dev.yml syntax is valid"
        fi
    
    - name: Validate environment files
      run: |
        # Check if environment files have valid syntax
        for env_file in *.env; do
          if [ -f "$env_file" ]; then
            echo "Checking $env_file..."
            # Basic validation - check for proper key=value format
            if grep -qE '^[A-Za-z_][A-Za-z0-9_]*=' "$env_file"; then
              echo "✅ $env_file has valid format"
            else
              echo "❌ $env_file may have invalid format"
              exit 1
            fi
          fi
        done
        
        # Check .env.example if it exists
        if [ -f .env.example ]; then
          echo "Checking .env.example..."
          if grep -qE '^[A-Za-z_][A-Za-z0-9_]*=' .env.example; then
            echo "✅ .env.example has valid format"
          else
            echo "❌ .env.example may have invalid format"
            exit 1
          fi
        fi
    
    - name: Test Docker Compose services can start
      run: |
        # Create minimal test environment
        echo "DATA_DIR=test-data" > .env
        
        # Try to pull images and validate service definitions
        docker-compose -f cosmos.yml pull --quiet || true
        echo "✅ Docker Compose services are properly defined"
        
        # Cleanup
        rm -f .env
    
    - name: Validate Makefile targets
      run: |
        # Check if Makefile has proper syntax and common targets
        make --dry-run help 2>/dev/null || echo "No help target found"
        make --dry-run up 2>/dev/null && echo "✅ 'up' target is valid" || echo "⚠️  'up' target not found"
        make --dry-run down 2>/dev/null && echo "✅ 'down' target is valid" || echo "⚠️  'down' target not found"
        make --dry-run clean 2>/dev/null && echo "✅ 'clean' target is valid" || echo "⚠️  'clean' target not found"
        echo "✅ Makefile syntax validation completed"
